### ISSUE TITLE
Livro

### ISSUE THREAD

**Issue by Saiuke** [flaviomicheletti/php-programando-com-orientacao-a-objetos#1]
Olá Flávio. Moro no exterior e estava precisando desse livro. Na Web não se encontra e-books para vender. E os únicos PDFs que se encontra são da edição 1. Você por acaso tem a edição 2 ou 3 em PDF ou e-book?

**Comment by flaviomicheletti** [comment]
Oi @Saiuke , rapaz não tenho não. Eu tenho só a primeira edição impressa. Abs.
